version: '3.8'
services:
  mnist-inference:
    build:
      context: .
      dockerfile: mount.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    command: uvicorn inference:app --host 0.0.0.0 --port 8000 --reload --log-level debug --timeout-keep-alive 75 --workers 1
    deploy:
      resources:
        limits:
          memory: 4G